version = 0.1
[default.deploy.parameters]
stack_name = "aws-s3-lambda-aurora-datasync"
resolve_s3 = true
s3_prefix = "aws-s3-lambda-aurora-datasync"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DBClusterName=\"aurora-test-cluster\" DatabaseName=\"aurora_test_db\" DBAdminUserName=\"admin_user\""
image_repositories = []
